spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/wordcloud
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
    hikari:
      max-lifetime: 600000

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        default-requeue-rejected: false
        concurrency: 4
        max-concurrency: 8
        prefetch: 10
        retry:
          enabled: true
          initial-interval: 1000
          max-attempts: 3
          multiplier: 2.0