spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/wordcloud
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest